/**
 * Nigerian VAT Exempted Items
 * This file contains comprehensive lists of items exempted from VAT in Nigeria
 * categorized by type of exemption.
 */

export const exemptedItems = {
  medicalAndPharmaceutical: [
    "medicine",
    "drug",
    "medication",
    "pharmaceutical",
    "pharmacy",
    "hospital",
    "clinic",
    "healthcare",
    "health care",
    "medical",
    "prescription",
    "treatment",
    "therapy",
    "doctor",
    "healthcare provider",
    "medical equipment",
    "medical supplies",
    "medical device",
    "surgical",
    "vaccine",
    "immunization",
    "diagnostic",
    "ambulance",
    "first aid",
    "bandage",
    "antiseptic",
    "antibiotic",
    "painkiller",
    "analgesic",
    "paracetamol",
    "ibuprofen",
    "aspirin",
    "cough syrup",
    "ointment",
    "inhaler",
    "insulin",
    "vitamin",
    "supplement",
    "blood pressure",
    "thermometer",
    "stethoscope",
    "wheelchair",
    "walking stick",
    "crutch",
    "syringe",
    "needle",
    "catheter",
    "defibrillator",
    "stretcher",
    "lab test",
    "x-ray",
    "ultrasound",
    "scan",
    "blood test",
    "hospital bed",
    "oxygen",
    "sanitizer",
    "disinfectant",
    "face mask",
    "glove",
    "contraceptive",
    "family planning",
    "prenatal",
    "dental care",
    "eye care",
    "malaria",
    "fever",
    "typhoid",
  ],
  basicFoodItems: [
    "rice",
    "beans",
    "yam",
    "cassava",
    "maize",
    "corn",
    "milk",
    "fruit",
    "vegetable",
    "bread",
    "cereals",
    "grain",
    "flour",
    "pasta",
    "egg",
    "potato",
    "tomato",
    "onion",
    "garri",
    "semovita",
    "wheat",
    "sugar",
    "salt",
    "cooking oil",
    "palm oil",
    "groundnut",
    "legume",
    "tuber",
    "plantain",
    "banana",
    "meat",
    "fish",
    "poultry",
    "seafood",
    "beef",
    "chicken",
    "water",
    "unprocessed food",
    "eba",
    "amala",
    "fufu",
    "pounded yam",
    "ogi",
    "pap",
    "akamu",
    "tuwo",
    "jollof rice",
    "ofada rice",
    "basmati rice",
    "local rice",
    "coconut rice",
    "guinea corn",
    "millet",
    "sorghum",
    "oats",
    "barley",
    "crayfish",
    "stockfish",
    "dry fish",
    "ponmo",
    "suya",
    "shaki",
    "kpomo",
    "goat meat",
    "bush meat",
    "catfish",
    "tilapia",
    "mackerel",
    "titus",
    "pepper soup",
    "ogbono",
    "egusi",
    "okra",
    "efo",
    "vegetable soup",
    "banga soup",
    "honey",
    "coco yam",
    "irish potato",
    "sweet potato",
    "coconut",
    "agidi",
    "edikaikong",
    "moin moin",
    "akara",
    "ewedu",
    "eba",
    "okpa",
    "abacha",
    "ugali",
    "okpa",
    "ukwa",
    "ogbono",
    "cashew nut",
    "kuli kuli",
    "zobo",
    "kunu",
    "agege bread",
    "cabin biscuit",
    "pure water",
    "table water",
    "bottled water",
    "coconut water",
    "borehole water",
    "cow milk",
    "goat milk",
    "soy milk",
    "almond milk",
    "coconut milk",
    "powdered milk",
    "liquid milk",
    "fresh milk",
    "yogurt",
  ],
  educationalMaterials: [
    "book",
    "textbook",
    "educational material",
    "school",
    "learning",
    "teaching",
    "notebook",
    "exercise book",
    "pencil",
    "pen",
    "crayon",
    "educational equipment",
    "school supplies",
    "stationery",
    "educational book",
    "academic",
    "ruler",
    "eraser",
    "sharpener",
    "calculator",
    "mathematical set",
    "compass",
    "protractor",
    "school bag",
    "backpack",
    "highlighter",
    "marker",
    "whiteboard",
    "blackboard",
    "chalk",
    "drawing book",
    "graph paper",
    "notepad",
    "folder",
    "file",
    "binder",
    "library book",
    "reference book",
    "dictionary",
    "encyclopedia",
    "atlas",
    "globe",
    "map",
    "science kit",
    "laboratory equipment",
    "school uniform",
    "education software",
    "digital learning",
    "e-learning",
    "online course",
    "educational video",
    "tutorial",
    "workbook",
    "study guide",
    "practice book",
    "flashcard",
    "educational toy",
    "school fee",
    "tuition",
    "exam fee",
    "educational poster",
    "drawing paper",
    "art supplies",
    "paintbrush",
    "watercolor",
    "poster color",
    "examination pad",
    "jotter",
    "geometry set",
  ],
  babyProducts: [
    "baby",
    "infant",
    "toddler",
    "diaper",
    "formula",
    "baby food",
    "baby milk",
    "baby clothing",
    "baby toiletries",
    "baby lotion",
    "baby oil",
    "baby powder",
    "baby wipe",
    "baby shampoo",
    "baby soap",
    "baby cream",
    "baby toy",
    "baby blanket",
    "baby bottle",
    "baby monitor",
    "crib",
    "cradle",
    "stroller",
    "pacifier",
    "teether",
    "baby carrier",
    "baby walker",
    "nappy",
    "baby cereal",
    "infant formula",
    "breast pump",
    "nursing pad",
    "maternity pad",
    "baby bath",
    "baby bib",
    "baby spoon",
    "sippy cup",
    "feeding bottle",
    "sterilizer",
    "baby detergent",
    "baby fabric softener",
    "potty",
    "changing table",
    "changing mat",
    "diaper bag",
    "diaper rash cream",
    "baby thermometer",
    "nasal aspirator",
    "infant medicine",
    "gripe water",
    "baby cotton swab",
    "baby nail clipper",
    "teething gel",
    "baby hat",
    "baby mittens",
    "baby socks",
    "baby shoes",
    "baby cot",
    "bassinet",
    "playpen",
    "baby swing",
    "high chair",
    "booster seat",
    "car seat",
    "baby gate",
    "bottle warmer",
    "milk storage bag",
    "baby pillow",
    "swaddle",
    "onesie",
    "romper",
    "baby vest",
    "baby wrapper",
    "shawl",
    "pampers",
    "huggies",
    "pre-natal vitamin",
    "post-natal vitamin",
    "stretch mark cream",
  ],
  agriculturalEquipment: [
    "farm equipment",
    "farm machinery",
    "tractor",
    "plough",
    "harvester",
    "irrigation"
    // ... more agricultural terms
  ],
  // Other exemption categories can be added here
};

// Common synonym mappings for better matching
export const synonymMap: Record<string, string[]> = {
  medicine: ["drug", "medication", "pill", "tablet", "capsule", "syrup"],
  medication: ["medicine", "drug", "pill", "tablet", "capsule", "syrup"],
  drug: ["medicine", "medication", "pill", "tablet", "capsule"],
  pill: ["medicine", "drug", "medication", "tablet", "capsule"],
  food: ["meal", "ingredient", "edible", "grocery", "provision"],
  education: ["learning", "school", "teaching", "study", "academic"],
  textbook: ["book", "manual", "workbook", "coursebook"],
  baby: ["infant", "toddler", "newborn", "child"],
  infant: ["baby", "toddler", "newborn", "child"],
  agriculture: ["farming", "farm", "crop", "cultivation", "livestock"],
  farming: ["agriculture", "farm", "crop", "cultivation", "livestock"],
};

// Export formatted category names for display
export const formatCategoryName = (catName: string): string => {
  return catName
    .replace(/([A-Z])/g, " $1") // Add spaces before capital letters
    .split(/\s+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(" ");
};

// Category-specific exemption details
export const exemptionDetails: Record<string, { details: string; legalBasis: string }> = {
  medicalAndPharmaceutical: {
    details: "Medical and pharmaceutical products are VAT-exempt to ensure healthcare remains accessible and affordable for all citizens.",
    legalBasis: "VAT Act First Schedule, Part I, Item 2"
  },
  basicFoodItems: {
    details: "Basic food items are exempt from VAT to protect citizens from additional tax burden on essential nutrition.",
    legalBasis: "VAT Act First Schedule, Part I, Item 1"
  },
  educationalMaterials: {
    details: "Educational materials are VAT-exempt to promote learning and reduce barriers to education.",
    legalBasis: "VAT Act First Schedule, Part I, Item 3"
  },
  babyProducts: {
    details: "Baby products are exempt from VAT to support families and ensure essential childcare items remain affordable.",
    legalBasis: "VAT Act First Schedule, Part I, Item 4"
  },
  agriculturalEquipment: {
    details: "Agricultural equipment is VAT-exempt to support farming activities and food production in Nigeria.",
    legalBasis: "VAT Act First Schedule, Part I, Item 5"
  },
  exportServices: {
    details: "Export services are VAT-exempt to promote international trade and Nigerian exports.",
    legalBasis: "VAT Act First Schedule, Part I, Item 6"
  }
}; 